### ISSUE TITLE
Feature Request: Support React 16

### ISSUE THREAD

**Issue by lscheibel** [nytimes/react-prosemirror#121]
I was wondering if the peer-dependency on React >= 17 could be dropped to >= 16. I am currently working with Apache Superset who, for various reasons, can't upgrade React in the near future. Are there any functions from React 17 that this library depends on?

**Comment by smoores-dev** [comment]
Oh shoot, I completely missed this, I'm so sorry for the delay. I don't _think_ there's any behavior or API we're relying on that requires React 17... we rely on `flushSync` (I'm not 100% sure when this was introduced but I believe it predates React 17) and hooks, which were introduced in 16.8.

@tilgovi can you think of any reason it would be a problem to require >=16.8, rather than >=17? We can do some testing, too

**Comment by tilgovi** [comment]
Let's try it. If bugs come up, we'll do our best and hopefully folks who need support can contribute.
