### ISSUE TITLE
`useNodePos` always reports position of `0`

### ISSUE THREAD

**Issue by saranrapjs** [nytimes/react-prosemirror#66]
It seems like:

- `useNodePos` depends on the `react` plugin being installed in an editor: https://github.com/nytimes/react-prosemirror/blob/main/src/hooks/useNodePos.tsx#L3
- but we don't appear to configure the `react` plugin for the ProseMirror component? and don't currently export the plugin to allow library consumers to use it

The net result is that `useNodePos` will always report a position of `0`, which leads to weird/unexpected editor behavior when dispatching transactions from within a nodeview which are position sensitive.

I'm guessing this may just have been an omission? I'd be happy to do the work to either export the plugin, or add it to the [plugins we already inject in `ProseMirrorInner`](https://github.com/nytimes/react-prosemirror/blob/main/src/components/ProseMirrorInner.tsx#L47)). Or both! But wanted to confirm my read of the problem here first, and make sure it wasn't intentional that we don't include that plugin (e.g. that the plugin isn't stable yet, or something like that).

**Comment by smoores-dev** [comment]
Oh shoot, this was indeed an omission. Because it's a state plugin, it can't be automatically injected (the other plugins are view prop only), but it should indeed be exported and the docs updated! I think this was just an ordering thing: #27 has the docs and exports the plugin, and I think I expected that to go out before `useNodePos` (whoops!).

Probably we should just merge and release #27; it really dramatically improves the react tree hierarchy and the only significant project I'm using this library in actually uses an alpha release that contains that change.

**Comment by saranrapjs** [comment]
I'm down to try to get that one towards a merge!

> Because it's a state plugin, it can't be automatically injected (the other plugins are view prop only), but it should indeed be exported and the docs updated

Can you say more about this? I'm not sure I understand the distinction — we don't want to inject plugins which store state, because we treat state as the concern of the React components which embed `ProseMirrorComponent`?

**Comment by smoores-dev** [comment]
Not a matter of want! EditorView throws an error if you pass plugins to its constructor that contain state fields: https://github.com/ProseMirror/prosemirror-view/blob/master/src/index.ts#L563-L566

**Comment by saranrapjs** [comment]
wow, "today I learned"!
