### ISSUE TITLE
controlled components in a `createPortal` from within a React NodeView behave weirdly

### ISSUE THREAD

**Issue by saranrapjs** [nytimes/react-prosemirror#69]
In this [demo branch](https://github.com/nytimes/react-prosemirror/compare/portal-bug-demo), we have an example "image" NodeView component which:

- renders a controlled component into a React portal, using a value from a ProseMirror node's attribute as the `value` prop for an `input`
- uses a `useEditorEventCallback` to update the ProseMirror node's attribute value in the ProseMirror document

https://github.com/nytimes/react-prosemirror/blob/357c65a41ed5576bb4d95e8245f6feb71e5e140f/demo/main.tsx#L90-L111

When making changes in the browser to the controlled component, the browser selection "resets" to the left side of the input (even though the update does "take" to the field):

![selection-jump](https://github.com/nytimes/react-prosemirror/assets/707098/24e2c1d2-05d0-4d6b-a55a-61c6727987cd)

What appears to be happening is that there's an extra React render cycle happening after the `useEditorEventCallback` is called, but before the corresponding update to the ProseMirror document "arrives" at the Node's `attrs`.

I'm not 100% sure this is portal specific, but can say that doing something equivalent from outside the editor (e.g. dispatching a transaction for a controlled component rendered in a separate React component that's a sibling or elsewhere in the React hierarchy) does not exhibit this issue.

**Comment by smoores-dev** [comment]
This kind of thing _usually_ happens when a component remounts, rather than just rerendering? I haven't taken a look at the branch yet, much I wonder if that's somehow what's happening here (like, a key is changing, or a component is being defined dynamically, or something?)

**Comment by saranrapjs** [comment]
I added a `useEffect(() => console.log("HI!"), [])` which only executes once, so i'm pretty sure it's not the component unmounting/remounting (but not 100% sure).

**Comment by smoores-dev** [comment]
Ah, alright! So here's what's happening:

1. User types something into the input
2. `onChange` is called, which calls `dispatchTransaction`, which updates the state of the `ProseMirrorInner` component
3. The React tree renders because of the state update, but the EditorView's state has not been updated yet, so all of the node views still have references to the nodes from the previous render (this is expected)
4. The input, which is a child of ProseMirrorInner, is rendered with the node from the old state, so its value is forcibly reset to the previous value (this resets the selection because React doesn't really have any other good options)
5. The `useLayoutEffect` in `useEditorView` runs, updating the state on the EditorView
6. The EditorView calls the update methods on all of its node views, which triggers state updates for their nodes, and so the Image component and its input are re-rendered with the new, updated node value.

In basically all scenarios other than this one, where there's an input inside of a node view component, this extra render is fine and dandy.

As a workaround for this use case, you can split out the input into its own component and React.memo it. I _think_ this is safe. Then it won't be re-rendered when it's passed the same node again. I just pushed a commit to your branch demonstrating this!

**Comment by smoores-dev** [comment]
(This is not an issue in the new architecture, because state is updated immediately, rather than in a layout effect!)

**Comment by saranrapjs** [comment]
> As a workaround for this use case, you can split out the input into its own component and React.memo it. I think this is safe. Then it won't be re-rendered when it's passed the same node again. I just pushed a commit to your branch demonstrating this!

This is clever! Thank you for thinking thru this

> (This is not an issue in the new architecture, because state is updated immediately, rather than in a layout effect!)

I figured — this seemed like very classic "React and prosemirror-view update on different cadences" territory!

**Comment by tilgovi** [comment]
Do we need this open for more discussion or are we content with the state of things?

**Comment by saranrapjs** [comment]
I'm happy to close unless we want to maintain a comprehensive list of "issues we believe to be resolved by new architecture" — though I haven't literally confirmed that it works there, for what it's worth.

**Comment by tilgovi** [comment]
Closing because this is solved by memoization, but I can see this being a real trap for folks until we move to a purely React-based view.
