### ISSUE TITLE
Upading EditorState does not update the view

### ISSUE THREAD

**Issue by petervelosy** [nytimes/react-prosemirror#76]
React-Prosemirror is being set up as follows:

```
const [mount, setMount] = useState(null);
const [editorState, setEditorState] = useState(EditorState.create({
    doc: defaultSchema.nodeFromJSON(data),
    schema: defaultSchema,
    plugins: getPlugins()
}));

<ProseMirror
          mount={mount}
          state={editorState}
          dispatchTransaction={(tr) => {
            setEditorState((s) => s.apply(tr));
          }}
      >
  <div ref={setMount} />
</ProseMirror>
```

When I load an external document into this editor by executing:

```
const newEditorState = editorState;
newEditorState.doc = defaultSchema.nodeFromJSON(data);
setEditorState(newEditorState);
```

The editor view does not refresh with the new document until I manually edit the editor's text area. After manually performing some edit, causing the view to refresh, the document is being displayed properly.

**Comment by smoores-dev** [comment]
Hmmm that's surprising! Can you share more about the context where that second code snippet is running? Is it in a callback or effect? The only "special" thing that `dispatchTransaction` does in the situation you've described is wrap itself in `flushSync`. That should only make sure that the render is committed to DOM before the call to `dispatch` finishes, but maybe there's something I'm missing there. If you could make a codepen or something demonstrating the issues that would make it easier for me to take a look!

**Comment by petervelosy** [comment]
@smoores-dev Here is a CodeSandbox showing the issue: https://codesandbox.io/p/sandbox/clever-herschel-zrmlph

Click on "Load ADF document into editor" and then perform some edit in order to make the view update. Unfortunately, you will get an exception `looks like multiple versions of prosemirror-model were loaded` along the way, as it seems that CodeSandbox does not process the "resolutions" object in package.json (this does not occur locally). The document (an Atlassian ADF) gets nevertheless properly loaded into the editor.

**Comment by petervelosy** [comment]
Update: Using `EditorState.create()` to create a brand new EditorState actually does refresh the view. However, updating some properties of the current EditorState and calling setEditorState() with it (as seen in the CodeSandbox) does not (even though the underlying data also gets updated in this case).

**Comment by smoores-dev** [comment]
Ah, I see what you're saying now. Yeah, that won't work! Two issues:

1. React relies on object references to know when state updates happen and re-renders should occur. Since you're using the same EditorState object, React doesn't actually know that anything has changed
2. EditorStates themselves maintain state tied to the doc, so you can't just hot-spot the doc like that

I think what you actually want to do here is produce a new EditorState. If there are parts of the EditorState that you want to copy over, like plugins, you can handle those as needed.

This doesn't seem to be an issue with react-prosemirror, so I'm going to close this issue for now!
