### ISSUE TITLE
Hook names are verbose

### ISSUE THREAD

**Issue by tilgovi** [nytimes/react-prosemirror#8]
I had originally envisioned the hooks as having names that were short and sweet, but I think there was some concern that they should be descriptive enough to be obviously associated with ProseMirror. I'm still drawn to short alternatives though, and wonder what other folks think.

- `useEditorState` -> `useEditorState` (no change)
- `useEditorView` -> `useEditorView` (no change)
- `useEditorViewLayoutEffect` -> `useEditorEffect`
- `useEditorViewEvent` -> `useEditorEvent`
- `useNodeViews` -> `useNodeViews` (no change)

**Comment by SMores** [comment]
I think I've figured out what's challenging for me about these, at least:

The obvious point of comparison here is React Redux/Redux Toolkit, which exports `useDispatch` and `useSelector`. What's really nice about those hooks is that they don't have any "namespacing" in them; it's not `useReduxDispatch`.

The issue that _we_ have is that `useLayoutEffect` _already exists_, and `useEvent` probably will soon, and so we can't just drop the namespacing.

Anyway, I am coming around a bit to `Editor` as the namespacing, though I still think it feels too broad. `ProseMirror` is technically a longer word than `EditorView`, but maybe feels like one conceptual chunk rather than two? `ProseMirror` seems more useful of a discriminator to me than just `Editor`. But you can always rename something when you import it if it's confusing in your application so maybe this is just bikeshedding.

Last thought: I don't have an opinion on this, I just want to make sure we're acknowledging the proposal to drop `Layout` from `useEditorViewLayoutEffect` here. The kinds of effects that would go in this hook are the kinds of effects that would go in a layout effect, so I would maybe be worried that his was a point of confusion? But if there's precedence for this, or we just don't think it matters, then that's fine.

**Comment by tilgovi** [comment]
My feeling about keeping them short was that folks may well find that `Editor` is sufficient namespacing, so prefer that. As you said, folks can rename if they need to.

I would drop `Layout` from the effect name because I don't think layout / non-layout is the meaningful distinction to make anymore. These are effects for the editor, and that's really the important part. I don't know that it's necessary to call attention to the fact that an editor's effects should be realized on layout.

Here's an exercise: if there were both `useEditorEffect` and `useEditorLayoutEffect`, what would the implementation of `useEditorEffect` be? I think it would _maybe_ just be `useEffect`, but gets the view as an argument? I can't think of a use case for wanting a reference to the view for things other than its layout functions, though. I could be convinced to keep `useEditorLayoutEffect` _for now_, but I suspect there'll never being a reason for `useEditorEffect`, and we may just want to adopt that alias down the road.

**Comment by tilgovi** [comment]
Good callout, though. I didn't say anything about dropping `Layout` in my issue, and it is important to discuss.
