### ISSUE TITLE
Hook to access EditorView directly

### ISSUE THREAD

**Issue by BrianHung** [nytimes/react-prosemirror#94]
Ran into a bug using `useEditorEventCallback` conditionally, resulting in

```js
Uncaught Error: Rendered fewer hooks than expected. This may be caused by an accidental early return statement.
```

The code that produced the bug was

```tsx
	return (
		<div
			aria-label="Typeahead menu"
			role="listbox"
		>
			{menuState.items.length > 0 ? (
				<ul className="pb-2">
					{menuState.items.map((item, index, items) => {
						const menuItemProps = {
							key: item.title,
							onClick: useEditorEventCallback(view => {
								if (view) {
									item.run(view.state, view.dispatch);
								}
							}),
						};
						return [
							<li {...menuItemProps}>
							</li>,
						];
					})}
				</ul>
			) : (
				<div
					onClick={useEditorEventCallback(view => {
						if (view) clearQuery(view.state, view.dispatch);
					})}
				>
				</div>
			)}
		</div>
	);
```

where because [`useEditorEventCallback`](https://github.com/nytimes/react-prosemirror/blob/main/src/hooks/useEditorEventCallback.ts) is a wrapper around `React.useCallback`, we can't use it conditionally.

To fix the bug, I had to create a separate `MenuItem` component for each item. 

However, I think another solution to this would be introduce a `const view = useEditorView()` hook that allows component to directly access the `EditorView`.

Reading though the docs, I do understand the possibility of confusion for developers if there is both `useEditorView` and `useEditorState`. And for dispatches, `view.state` should be used while for UI, normal `state` should be used instead.

It feels very analogous to a thing I saw in [valtio](https://github.com/pmndrs/valtio), where you have a separate read-only snapshot of the last state (EditorState), and a separate mutable / write-only state (EditorView).

Thoughts?

**Comment by smoores-dev** [comment]
I think this is a pretty common occurrence in the React Hooks world, and the standard guidance is to break your menu item out into a separate component, so that each can unconditionally call the `useEditorEventCallback` hook (as you've done!). This is true for `useCallback` (and `useMemo` and `useState`, etc) as well!

I don't think we're likely to ever expose the EditorView directly in the render function; the `useEditorEventCallback` and `useEditorEffect` hooks are precisely the two places that the EditorView is safe to access. This is one of the key selling points of this library: it makes it hard to shoot yourself in the foot by unintentionally introducing state tearing. Even ignoring `view.state`, it's too easy to unintentionally introduce inconsistencies when accessing, e.g., `view.coordsAtPos()` is based on both `view.state` _and_ `view.dom`, neither of which match the state from `useEditorState()` in the render function. Rather than providing the EditorView directly, and then relying on consumers to know how and when it's safe to access, this library always prefers to only expose the EditorView when it's already safe to access.

**Comment by BrianHung** [comment]
> This is one of the key selling points of this library: it makes it hard to shoot yourself in the foot by unintentionally introducing state tearing.

Ah, I do see your perspective. React hook errors are a common pitfall, but easier to solve than introducing more complexity to developers.

I just wish the console specified that it was useEditorEventCallback that was missing in the error stack. 😅
